[phases.setup]
nixPkgs = ['nodejs_18', 'yarn']

[phases.install]
cmds = ['yarn install']

[phases.build]
cmds = ['yarn build']

[start]
cmd = './start.sh'

[variables]
NODE_ENV = 'production'
PORT = '9000'
