services:
  - type: web
    name: medusa-backend
    env: node
    plan: free
    buildCommand: yarn install && yarn build && npx medusa build --admin-only && npx medusa db:migrate
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: medusa_super_secret_jwt_2024_secure_render
      - key: COOKIE_SECRET
        value: medusa_super_secret_cookie_2024_secure_render
      - key: MEDUSA_ADMIN_ONBOARDING_TYPE
        value: nextjs
      - key: STORE_CORS
        value: http://localhost:3000
      - key: ADMIN_CORS
        value: http://localhost:9000
      - key: AUTH_CORS
        value: http://localhost:3000,http://localhost:9000
      - key: DATABASE_URL
        fromDatabase:
          name: medusa-database
          property: connectionString

databases:
  - name: medusa-database
    databaseName: medusa
    user: medusa
    plan: free
